#!/usr/bin/env zsh
# VDE USP Hydration Script: dynamic-pkg-vm
# Part of the Universal Script Parity (USP) mandate.
# Forged in Beskar
set -e

# 1. THE PACKAGE ALLOY
export DEBIAN_FRONTEND=noninteractive
local vde_dynamic-pkg-vm_pkgs=""

# 2. THE FORGE WORK
apt-get update -y && apt-get install -y htop

# 3. PURGING THE GHOSTS
apt-get clean
rm -rf /var/lib/apt/lists/*
